# Pandas. Домашнее задание

В домашнем задании есть обязательные и дополнительные задачи.

*Обязательные задачи* нужно сделать, чтобы проверить, что вы действительно усвоили материал модуля. Они обязательны к загрузке на проверку преподавателю.

*Дополнительные задачи* для тех, кто чувствует, что нужно ещё немного потренироваться и порешать задачки по работе с Pandas. Вы также можете загрузить их на проверку преподавателю и получить по ним обратную связь.

Удачи!



---



---



**Обязательные задачи**

В течение всего домашнего задания вы будете работать с несколькими наборами данных:
1. Набор рекламных данных, показывающих, щёлкнул ли конкретный пользователь рекламу на сайте компании или нет. Состоит из трёх разных файлов: `advertising_1.csv`, `advertising_2.csv`, `advertising_3.csv`.

Описание столбцов датасета:
- **Number**: Номер пользователя в системе.
- **Daily Time Spent on Site**: Среднее ежедневное время нахождения пользователя на сайте в минутах.
- **Daily Internet Usage**: Среднее ежедневное время нахождения пользователя в интернете в минутах.
- **Ad Topic Line**: Заголовок рекламного объявления.
- **Clicked on Ad**: Кликнул пользователь на рекламу или нет.

Дополнительный к рекламным данным датасет, который описывает пользователей, посещающих сайт компании. Состоит из одного файла: users.csv.

Описание столбцов датасета:
- **Number**: Номер пользователя в системе.
- **Age**: Возраст пользователя.
- **Male**: Является ли пользователь мужчиной.
- **City**: Город пользователя.
- **Country**: Страна пользователя.
- **Area Income**: Средний доход в месте жительства пользователя.


***Задача 1***

Загрузите таблицу из файла `advertising_1.csv` и сохраните её в датафрейм `adv1_df`. Укажите в качестве индекса столбец `Number`. Выведите на экран первые десять строк.


In [204]:
import pandas as pd

adv1_df = pd.read_csv('advertising_1.csv', index_col='Number')
adv1_df.head(10)

Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
5                          68.95                256.09   
6                          80.23                193.77   
8                          74.15                245.89   
9                            NaN                225.58   
10                         59.99                226.74   
11                         88.91                208.36   
12                           NaN                131.76   
13                         74.53                   NaN   
14                         69.88                183.82   
15                         47.64                122.02   

                                Ad Topic Line  Clicked on Ad  
Number                                                        
5          Cloned 5thgeneration orchestration              0  
6          Monitored national standardization              0  
8       Triple-buffered reciprocal time-frame              0  
9               Robust logistical utilization              0  
10            Sharable client-driven software              0  
11                 Enhanced dedicated support              0  
12                   Reactive local challenge              1  
13             Configurable coherent function              0  
14         Mandatory homogeneous architecture              0  
15             Centralized neutral neural-net              1

***Задача 2***

Выведите размер датафрейма `adv1_df`.

In [205]:
adv1_df.count()

Daily Time Spent on Site    450
Daily Internet Usage        448
Ad Topic Line               500
Clicked on Ad               500
dtype: int64

***Задача 3***

Выведите cреднее ежедневное время нахождения в интернете пользователя под номером 8.

In [206]:
adv1_df.loc[8, 'Daily Internet Usage']

245.89

***Задача 4***

Загрузите таблицу из файла `advertising_2.csv` и сохраните её в датафрейм `adv2_df`. Укажите в качестве индекса стоблец `Number`. Выведите на экран строки для пользователей с номерами с 533-го по 536-й.

In [207]:
adv2_df = pd.read_csv('advertising_2.csv', index_col='Number')
adv2_df.loc[533:536, :]

Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
533                        46.61                   NaN   
534                          NaN                162.03   
535                        65.10                118.10   
536                        53.44                   NaN   

                                Ad Topic Line  Clicked on Ad  
Number                                                        
533             Ergonomic methodical encoding              1  
534         Compatible dedicated productivity              0  
535            Up-sized real-time methodology              1  
536     Up-sized next generation architecture              1

***Задача 5***

Выведите сводную таблицу описательных статистик для датафрейма `adv2_df`, вызвав необходимый метод на всём датафрейме. 

Глядя на вывод, напишите, столбец с каким названием не содержит незаполненных значений.

*Подсказка:*  В сводной таблице не содержится информации о количестве строк всего датафрейма, поэтому для сначала распечатайте общее количество строк датафрейма.

*Рекомендация:* Кроме изученного метода `describe` для описания датафрейма и получения информации о пропущенных значениях полезен метод [`info`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html).

In [208]:
adv2_df.count()

Daily Time Spent on Site    184
Daily Internet Usage        184
Ad Topic Line               200
Clicked on Ad               200
dtype: int64

In [209]:
# Ваш код здесь
print('Не содержит незаполненных значений столбец:', 'Number', 'Ad Topic Line', 'Clicked on Ad')

Не содержит незаполненных значений столбец: Number Ad Topic Line Clicked on Ad


***Задача 6***

Добавьте к датафрейму `adv1_df` в конец датафрейм `adv2_df` с помощью метода `append`. 

Сохраните объединенный датафрейм в новой переменной `adv12_df` и распечатайте его.

In [210]:
adv12_df = adv1_df.append(adv2_df)
adv12_df.loc[490:510, :]

Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
490                        66.88                   NaN   
491                        83.97                158.42   
492                        76.56                213.75   
493                        35.49                159.77   
494                        80.29                244.87   
495                        50.19                117.30   
496                        59.12                124.54   
497                        59.88                193.63   
498                        59.70                120.25   
499                        67.80                117.75   
500                        81.59                223.16   
501                        81.10                216.49   
502                        41.70                126.95   
503                        73.94                173.49   
504                        58.35                132.63   
505                        51.56                124.85   
506                        79.81                253.17   
507                          NaN                228.70   
508                          NaN                105.94   
509                        66.12                113.80   
510                        80.47                   NaN   

                                       Ad Topic Line  Clicked on Ad  
Number                                                               
490                       Polarized bifurcated array              1  
491                 Progressive asynchronous adapter              0  
492             Business-focused high-level hardware              0  
493           Fully-configurable holistic throughput              1  
494     Ameliorated contextually-based collaboration              0  
495         Progressive uniform budgetary management              1  
496                Synergistic stable infrastructure              1  
497        Reverse-engineered content-based intranet              0  
498            Expanded zero administration attitude              1  
499             Team-oriented 6thgeneration extranet              1  
500               Managed disintermediate capability              0  
501                         Front-line dynamic model              0  
502                    Innovative regional structure              1  
503       Function-based incremental standardization              0  
504                   Universal asymmetric workforce              1  
505          Business-focused client-driven forecast              1  
506                      Realigned global initiative              0  
507            Business-focused maximized complexity              0  
508                      Open-source global strategy              1  
509                Stand-alone motivating moratorium              1  
510                    Grass-roots multimedia policy              0

***Задача 7***

Для объединённого датафрейма `adv12_df` распечатайте среднее время, проводимое пользователем на сайте компании.

In [211]:
round(adv12_df['Daily Time Spent on Site'].mean(), 2)

65.57

***Задача 8***

Из объединённого датафрейма `adv12_df` выберите и распечатайте строки только с теми пользователями, для которых неизвестно среднее ежедневное время, проводимое пользователем на сайте компании.

In [212]:
date_is_null = adv12_df[adv12_df['Daily Time Spent on Site'].isnull()]
date_is_null.head(20)


Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
9                            NaN                225.58   
12                           NaN                131.76   
19                           NaN                143.56   
27                           NaN                164.83   
34                           NaN                209.82   
55                           NaN                196.71   
60                           NaN                177.55   
71                           NaN                   NaN   
101                          NaN                154.02   
103                          NaN                158.22   
109                          NaN                202.16   
113                          NaN                135.18   
132                          NaN                206.98   
135                          NaN                175.37   
137                          NaN                176.73   
140                          NaN                160.03   
146                          NaN                163.00   
165                          NaN                195.31   
186                          NaN                168.34   
199                          NaN                254.05   

                                       Ad Topic Line  Clicked on Ad  
Number                                                               
9                      Robust logistical utilization              0  
12                          Reactive local challenge              1  
19                     Grass-roots coherent extranet              1  
27             Mandatory disintermediate utilization              1  
34           Business-focused value-added definition              0  
55                      Organized static focus group              0  
60                     Sharable bottom-line solution              0  
71                     Synchronized user-facing core              1  
101                   Versatile homogeneous capacity              1  
103                      Up-sized secondary software              1  
109           Polarized 6thgeneration info-mediaries              0  
113     Customer-focused upward-trending contingency              1  
132         Polarized bandwidth-monitored moratorium              0  
135                Down-sized well-modulated archive              1  
137                Versatile transitional monitoring              1  
140               Enhanced system-worthy application              1  
146           Re-contextualized optimal service-desk              1  
165                  Networked foreground definition              0  
186                   Stand-alone tangible moderator              1  
199                 Persistent homogeneous framework              0

***Задача 9***

Загрузите таблицу из файла `advertising_3.csv` и сохраните её в датафрейм `adv3_df`. Укажите в качестве индекса стоблец `Number`. Выведите на экран столбцы `Ad Topic Line` и `Clicked on Ad`.

In [213]:
adv3_df = pd.read_csv('advertising_3.csv', index_col='Number')
adv3_df.loc[:, ['Ad Topic Line', 'Clicked on Ad']]

Ad Topic Line  Clicked on Ad
Number                                                             
740                 Distributed bifurcated challenge              0
741       Customizable zero-defect Internet solution              0
742     Self-enabling zero administration neural-net              1
744           Open-architected system-worthy ability              0
745               Quality-focused maximized extranet              1
...                                              ...            ...
999                    Front-line bifurcated ability              1
1000                   Fundamental modular algorithm              1
1001                 Grass-roots cohesive monitoring              1
1002                    Expanded intangible solution              1
1003            Proactive bandwidth-monitored policy              0

[251 rows x 2 columns]

***Задача 10***

Добавьте к датафрейму `adv12_df` в конец датафрейм `adv3_df` с помощью метода `concat`. Явно пропишите значение параметра `axis`.

Сохраните объединённый датафрейм в новой переменной `adv123_df` и распечатайте его.

In [214]:
adv123_df = pd.concat([adv12_df, adv3_df], axis=0)
adv123_df

Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
5                          68.95                256.09   
6                          80.23                193.77   
8                          74.15                245.89   
9                            NaN                225.58   
10                         59.99                226.74   
...                          ...                   ...   
999                        43.70                173.01   
1000                       72.97                208.58   
1001                       51.30                   NaN   
1002                       51.63                120.37   
1003                       55.55                187.95   

                                Ad Topic Line  Clicked on Ad  
Number                                                        
5          Cloned 5thgeneration orchestration              0  
6          Monitored national standardization              0  
8       Triple-buffered reciprocal time-frame              0  
9               Robust logistical utilization              0  
10            Sharable client-driven software              0  
...                                       ...            ...  
999             Front-line bifurcated ability              1  
1000            Fundamental modular algorithm              1  
1001          Grass-roots cohesive monitoring              1  
1002             Expanded intangible solution              1  
1003     Proactive bandwidth-monitored policy              0  

[951 rows x 4 columns]

***Задача 11***

Для объединённого датафрейма `adv123_df` выберите только те строки, в которых пользователи кликнули на рекламное сообщение. Сохраните полученный результат в датафрейм `success_adv_df`, распечатайте размер нового датафрейма.

In [215]:
success_adv_df = adv123_df[adv123_df['Clicked on Ad'] == 1]
len(success_adv_df)

475

***Задача 12***

Загрузите таблицу с данными пользователей из файла `users.csv` и сохраните её в датафрейм `users_df`. Индекс не указывайте.

Распечатайте сам датафрейм и сводную таблицу со статистиками для него.

In [216]:
users_df = pd.read_csv('users.csv')
print(users_df)
print(users_df.describe())

     Number   Age  Male            City                 Country  Area Income
0         5   NaN   0.0     Wrightburgh                 Tunisia     61833.90
1         6  31.0   NaN       West Jodi                   Nauru     68441.85
2         7  26.0   0.0        Davidton              San Marino     59785.94
3         8  29.0   1.0  West Terrifurt                   Italy     54806.18
4         9   NaN   0.0    South Manuel                 Iceland     73889.99
..      ...   ...   ...             ...                     ...          ...
975    1000  30.0   NaN       Duffystad                 Lebanon     71384.57
976    1001  45.0   1.0     New Darlene  Bosnia and Herzegovina     67782.17
977    1002  51.0   NaN   South Jessica                Mongolia     42415.72
978    1003  19.0   0.0     West Steven               Guatemala     41920.79
979    1004  26.0   0.0     Ronniemouth                  Brazil     29875.80

[980 rows x 6 columns]
            Number         Age        Male   Area In

***Задача 13***

Глядя на статистики `users_df`, укажите значения, удовлетворяющие следующим условиям:
1. Возраст самого молодого пользователя сайта: 19
2. Максимальный средний доход в месте жительства пользователя сайта:79484.8
3. Средний возраст пользователя сайта: 36
4. Количество заполненных значений для колонки, содержащей информацию о том, является пользователь мужчиной или нет: 860
5. Минимальный номер пользователя: 5

В этом задании не требуется выбирать по условиям и распечатывать значения, достаточно внимательно посмотреть на статистики и скопировать нужные значения согласно вопросам.

***Задача 14***

К полученному датафрейму с успешными рекламными сообщениями `success_adv_df` добавьте справа информацию из датафрейма с пользователями `users_df` и сохраните в датафрейм `success_full_df`. В полученном датафрейме должны остаться только те пользователи, номера которых есть в обоих датафреймах. Для этого воспользуйтесь методом `merge` и пропишите явно верные параметры.

Затем распечатайте датафрейм.

*Важно:*

Объединять датафреймы с помощью `merge` можно и по индексам, и по столбцам с разными названиями. 
Так как общие значения содержатся в столбце `Number`, но в датафрейме `users_df` данный столбец является обычным столбцом, а в `success_adv_df` является индексом, перед тем как объединять, переведите столбец `Number` в `success_adv_df` в обычный столбец.

Для этого перед объединением пропишите:
```
success_adv_df = success_adv_df.reset_index()
```

[Подробнее о reset_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html)

In [217]:
success_adv_df = success_adv_df.reset_index()
succes_full_df = pd.merge(left=success_adv_df, right=users_df, on='Number', how='inner')
succes_full_df

Number  Daily Time Spent on Site  Daily Internet Usage  \
0        12                       NaN                131.76   
1        15                     47.64                122.02   
2        17                     69.57                113.12   
3        19                       NaN                143.56   
4        20                     63.45                140.64   
..      ...                       ...                   ...   
459     997                     69.17                123.62   
460     999                     43.70                173.01   
461    1000                     72.97                208.58   
462    1001                     51.30                   NaN   
463    1002                     51.63                120.37   

                             Ad Topic Line  Clicked on Ad   Age  Male  \
0                 Reactive local challenge              1  48.0   1.0   
1           Centralized neutral neural-net              1  49.0   NaN   
2    Centralized content-based focus group              1  48.0   1.0   
3            Grass-roots coherent extranet              1  33.0   0.0   
4       Persistent demand-driven interface              1  23.0   NaN   
..                                     ...            ...   ...   ...   
459          Extended leadingedge solution              1  40.0   NaN   
460          Front-line bifurcated ability              1  28.0   0.0   
461          Fundamental modular algorithm              1  30.0   NaN   
462        Grass-roots cohesive monitoring              1  45.0   1.0   
463           Expanded intangible solution              1  51.0   NaN   

                 City                 Country  Area Income  
0    Port Jefferybury               Australia     24593.33  
1     West Brandonton                   Qatar     45632.51  
2      West Katiefurt                   Egypt     51636.92  
3                 NaN                Barbados     30976.00  
4                 NaN                   Spain     52182.23  
..                ...                     ...          ...  
459       New Patrick              Montenegro     66193.81  
460      Nicholasland                 Mayotte     63126.96  
461         Duffystad                 Lebanon     71384.57  
462       New Darlene  Bosnia and Herzegovina     67782.17  
463     South Jessica                Mongolia     42415.72  

[464 rows x 10 columns]

***Задача 15***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, отобразите сводную таблицу со статистиками для строковых колонок (`Ad Topic Line`, `City`, `Country`).


In [218]:
succes_full_df[['Ad Topic Line', 'City', 'Country']].describe()

Ad Topic Line        City   Country
count                        464         420       418
unique                       464         412       203
top     Reactive local challenge  Lake James  Ethiopia
freq                           1           2         7

***Задача 16***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите страну и количество вхождений этой страны в датафрейм.


In [219]:
count_pop = succes_full_df.groupby('Country')['Country'].count().sort_values(ascending=False)
count_pop

Country
Ethiopia        7
Liberia         6
Turkey          6
Australia       6
South Africa    5
               ..
Greenland       1
Nauru           1
Namibia         1
Myanmar         1
Bhutan          1
Name: Country, Length: 203, dtype: int64

***Задача 17***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите строки с данными пользователей из страны, название которой встречается чаще остальных.


In [230]:
users_pop_country = succes_full_df[succes_full_df['Country'] == 'Ethiopia']

***Задача 18***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите строки с данными пользователей из страны, название которой встречается чаще остальных, они проводят в интернете в среднем больше 120 минут и их возраст меньше 30 лет. 
Cохраните получившиеся строки в новый датафрейм `filtered_df`.


In [235]:
filtered_df = users_pop_country[(users_pop_country['Daily Internet Usage'] > 120) &\
                    (users_pop_country['Age'] > 30)]

***Задача 19***

Для получившегося датафрейма `filtered_df` выведите строки с данными пользователей, для которых либо не указано среднее время, проведённое на сайте, либо указанное время больше 55 минут. Cохраните получившиеся строки в новый датафрейм `filtered_df2`.


In [249]:
filtered_df2 = filtered_df[filtered_df['Daily Time Spent on Site'].isnull()]
_ = filtered_df2[filtered_df2['Daily Time Spent on Site'] > 55]
filtered_df2 = filtered_df2.append(_)

**Дополнительные задачи**

***Задача 20***

Для датафрейма `adv123_df` выведите строки с данными, заголовок рекламного сообщения в которых включает слово `model`.

Для этого вам понадобится метод [`contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html).

Cохраните получившиеся строки в новый датафрейм `model_df`.


In [253]:
model_df = adv123_df[adv123_df['Ad Topic Line'].str.contains(pat='model')]

***Задача 21***

Для получившегося датафрейма `model_df` выведите строки с данными пользователей, которые проводят на сайте больше среднего времени по всем пользователям в данном датафрейме. Cохраните получившиеся строки в новый датафрейм `model_popular_df`.


In [274]:
avd_time = model_df['Daily Time Spent on Site'].mean()
model_popular_df = model_df[model_df['Daily Time Spent on Site'] > avd_time]
model_popular_df


Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
202                        78.57                   NaN   
211                        76.90                212.67   
501                        81.10                216.49   
538                        91.43                209.91   
629                        78.17                192.27   
712                        81.90                225.47   
823                        81.98                212.88   

                              Ad Topic Line  Clicked on Ad  
Number                                                      
202           Exclusive client-driven model              0  
211           Synchronized multimedia model              0  
501                Front-line dynamic model              0  
538                Organic motivating model              0  
629                  Automated mobile model              0  
712     Multi-channeled 3rdgeneration model              0  
823                Up-sized maximized model              0

***Задача 22***

Для объединённого датафрейма `model_popular_df` выведите строки с данными пользователей, номера которых равны 501, 712 и 823. 

Для этого вам понадобится метод [`isin`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html).

*Подсказка:* Не забудьте, что номера пользователей находятся не в обычной колонке, а в колонке, являющейся индексом, поэтому вам необходимо получить значения индекса, а не обычной колонки.

In [276]:
model_popular_df[model_popular_df.index.isin([501, 712, 823])]

Daily Time Spent on Site  Daily Internet Usage  \
Number                                                   
501                        81.10                216.49   
712                        81.90                225.47   
823                        81.98                212.88   

                              Ad Topic Line  Clicked on Ad  
Number                                                      
501                Front-line dynamic model              0  
712     Multi-channeled 3rdgeneration model              0  
823                Up-sized maximized model              0